config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  
  get 'pages/index'

  #Rotas montar selects
  get 'bancos/all'
  get 'contas/all'
  get 'pessoas/all'

  resources :contas
  resources :pessoas
  resources :bancos
  resources :movimentos
  
  devise_for :usuarios, :skip => [:registrations] 

  #Rotas JSON(País, Estado, Cidade)
  get 'enderecos/association'
  get 'enderecos/paises'
  get 'enderecos/:id/pais', to: 'enderecos#pais'
  get 'enderecos/estados'
  get 'enderecos/:id/estado', to: 'enderecos#estado'
  get 'enderecos/cidades'
  get 'enderecos/:id/cidade', to: 'enderecos#cidade'
end

app/models/banco.rb
class Banco < ApplicationRecord
  has_many :contas, :dependent => :delete_all
  
  validates :codigo, numericality: true, presence: true
  validates :descricao, presence: true
  
  def busca(id)
    Banco.find(id)
  end
  
  scope :codigo, -> (codigo) { where("codigo like ?", "%#{codigo}%")}
  scope :descricao, -> (descricao) { where("descricao like ?", "%#{descricao}%")}
end

app/controllers/bancos_controller.rb
class BancosController < ApplicationController
  before_action :set_banco, only: [:show, :edit, :update, :destroy]

  # GET /bancos
  # GET /bancos.json
  def index
    #Busca Banco
    @bancos = Banco.where(nil) #Inicia Escopo
    @bancos = @bancos.codigo(params[:codigo]) if params[:codigo].present?
    @bancos = @bancos.descricao(params[:descricao]) if params[:descricao].present?
    #End Busca Banco
    
    @bancos = @bancos.paginate(:page => params[:page], :per_page => params[:per_page])
    respond_to do |format|
      format.html { render :index }
      format.json { render json:{ bancos: @bancos, total: @bancos.total_entries } }
    end
  end


  # GET /bancos/1
  # GET /bancos/1.json
  def show
  end

  # GET /bancos/new
  def new
    @banco = Banco.new
  end

  # GET /bancos/1/edit
  def edit
  end

  # POST /bancos
  # POST /bancos.json
  def create
    @banco = Banco.new(banco_params)

    respond_to do |format|
      if @banco.save
        format.html { redirect_to(:bancos, :notice => t('activerecord.successful.messages.created', :model => @banco.class.model_name.human))}
        format.json { render :show, status: :created, location: @banco }
      else
        format.html { render :new }
        format.json { render :json => { :errors => @banco.errors.full_messages }, :status => 422 }
      end
    end
  end

  # PATCH/PUT /bancos/1
  # PATCH/PUT /bancos/1.json
  def update
    respond_to do |format|
      if @banco.update(banco_params)
        format.html { redirect_to(:bancos, :notice => t('activerecord.successful.messages.updated', :model => @banco.class.model_name.human))}
        format.json { render :show, status: :ok, location: @banco }
      else
        format.html { render :edit }
        format.json { render :json => { :errors => @banco.errors.full_messages }, :status => 422 }
      end
    end
  end

  # DELETE /bancos/1
  # DELETE /bancos/1.json
  def destroy
    @banco.destroy
    respond_to do |format|
      format.html { redirect_to(@banco, :notice => t('activerecord.successful.messages.destroyed', :model => @banco.class.model_name.human))}
      format.json { render :json => { :errors => @banco.errors.full_messages }, :status => 422 }
    end
  end

  #GET /bancos/all
  def all
    @bancos = Banco.all
    respond_to do |format|
      format.json{ render json: @bancos, :only => [:id, :descricao]}
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banco
      @banco = Banco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banco_params
      params.require(:banco).permit(:descricao, :codigo)
    end
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/views/bancos/_form.html.erb
<%= form_with(model: banco, local: true) do |form| %>
  <% if banco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(banco.errors.count, "error") %> prohibited this banco from being saved:</h2>

      <ul>
      <% banco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :descricao, "Descrição" %>
    <%= form.text_field :descricao, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :codigo, "Código do banco" %>
    <%= form.text_field :codigo, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class=> "btn btn-dark" %>
  </div>
<% end %>

app/views/bancos/edit.html.erb
<h1>Editar Banco</h1>

<%= render 'form', banco: @banco %>

<%= link_to 'Mostrar', @banco %> |
<%= link_to 'Voltar', bancos_path %>

app/views/bancos/index.html.erb
<div id="bancosApp" v-cloak class="container">
	<div class="table-wrapper">
	  <div class="table-title">
	      <div class="row">
	          <div class="col-sm-6">
	            <h2 class="text-light">Gerenciar <b>Bancos</b></h2>
	          </div>
	      		<div class="col-sm-6">
	      			<a href="#formBancoModal" class="btn btn-success" data-toggle="modal" @click="mountCreateForm()"><i class="material-icons">&#xE147;</i> <span>Novo</span></a>
	      			<a href="#deleteBancoModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Apagar</span></a>	
	      			<a class="btn btn-warning" @click="createPDF()"><i class="material-icons">&#xE873;</i> <span>PDF</span></a>
	      		</div>
	      </div>
	  </div>
	  <div class="search-wrapper">
		  <div class="form-row align-items-center">
		    <div class="col-md-4">
		      <label class="sr-only" for="inlineFormInput"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Código</div>
		        </div>
		        <input type="text" class="form-control" id="codigo" v-model="codigo">
		      </div>
		    </div>
		    <div class="col-md-7">
		      <label class="sr-only" for="inlineFormInputGroup"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Descrição</div>
		        </div>
		        <input type="text" class="form-control" id="descricao" v-model="descricao">
		      </div>
		    </div>
		     <div class="col-auto">
			  <a class="btn btn-primary mb-2 text-light" @click="searchBancos()"><span class="fa fa-search"></span></a>
			</div>
		  </div>
		</div>
	  <table class="table table-striped table-hover">
	    <thead>
	        <tr>
				<th>
					<span class="custom-checkbox">
						<input type="checkbox" id="selectAll" v-model="allSelected" @click="selectAll">
						<label for="selectAll"></label>
					</span>
				</th>
					<th>Código do Banco</th>
	        <th>Descrição</th>
	        <th>Ações</th>
	      </tr>
	    </thead>
	    <tbody>
    	<tr v-if="loading">
           <td>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                      <div class="ph-row">
                          <div class="ph-col-12"></div>
                      </div>
                  </div>
              </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
        </tr>
        <tr v-if="loading">
           <td>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                      <div class="ph-row">
                          <div class="ph-col-12"></div>
                      </div>
                  </div>
              </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
        </tr>
        <tr v-if="loading">
           <td>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                      <div class="ph-row">
                          <div class="ph-col-12"></div>
                      </div>
                  </div>
              </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
        </tr>
        <tr v-if="loading">
           <td>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                      <div class="ph-row">
                          <div class="ph-col-12"></div>
                      </div>
                  </div>
              </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
        </tr>
        <tr v-if="loading">
           <td>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                      <div class="ph-row">
                          <div class="ph-col-12"></div>
                      </div>
                  </div>
              </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
        </tr>
        <tr v-if="loading">
           <td>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                      <div class="ph-row">
                          <div class="ph-col-12"></div>
                      </div>
                  </div>
              </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
        </tr>
        <tr v-if="loading">
           <td>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                      <div class="ph-row">
                          <div class="ph-col-12"></div>
                      </div>
                  </div>
              </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
           <td>
              <div class="ph-item">
                  <div class="ph-col-12">
                   <div class="ph-row">
                       <div class="ph-col-12"></div>
                   </div>
               </div>
           </div>
           </td>
        </tr>
        <tr v-if="!loading" v-for="(banco, index) in bancos">
          <td>
            <span class="custom-checkbox">
              <input type="checkbox" :id="'checkbox'+banco.id" value="1" v-model="bancos[index].selected" @click="select">
              <label :for="'checkbox'+banco.id"></label>
            </span>
          </td>
          <td>{{ banco.codigo }}</td>
          <td>{{ banco.descricao }}</td>
          <td>
            <a href="#deleteBancoModal" data-toggle="modal" class="edit" @click="mountEditForm(banco)"><i class="material-icons" data-toggle="tooltip" title="Editar">&#xE254;</i></a>
            <a href="#deleteBancoModal" data-toggle="modal" class="delete" @click="mountDeleteForm(banco)"><i class="material-icons" data-toggle="tooltip" title="Apagar">&#xE872;</i></a>
          </td>
        </tr>
	    </tbody>
	  </table>
		<div class="text-center" v-if="loading">
			<div class="spinner-border" role="status">
				<span class="sr-only">Carregando...</span>
			</div>
		</div>
	  <div class="mt-3 text-right" v-if="total > 10">
		  <b-pagination align="right" :total-rows="total" :per-page="10" @change="changePage" />
	  </div>
	  <div class="hint-text">Mostrando <b>{{bancos.length }}</b> registros</div>
	  <br>
	</div>
	
	<b-modal ref="formBancoModal" title="Banco">
		<form>
		  <div class="field form-group">
		    <label for="banco_descricao">Descrição</label>
		    <input class="form-control" type="text" name="banco[descricao]" id="banco_descricao" v-model="clickedBanco.descricao">
		  </div>
		
		  <div class="field form-group">
		    <label for="banco_codigo">Código do banco</label>
		    <input class="form-control" type="text" name="banco[codigo]" id="banco_codigo" v-model="clickedBanco.codigo">
		  </div>
		</form>
		<div slot="modal-footer">
			<a class="btn btn-secondary text-light" @click="closeModal">Fechar</a>
			<a class="btn btn-success text-light" @click="createBanco(clickedBanco)" v-if="create"><span v-if="loading" class="spinner-border spinner-border-sm"></span> Salvar</a>
			<a class="btn btn-info text-light" @click="updateBanco(clickedBanco)" v-if="!create"> Atualizar</a>
		</div>
	</b-modal>
	<b-modal ref="deleteBancoModal" title="Apagar Banco">
		<p>Tem certeza que deseja apagar esse registro?</p>
		<p>Descrição: {{clickedBanco.descricao}}</p>
		<p>Código: {{clickedBanco.codigo}}</p>
		<p class="text-danger"><small>Esta ação não poderá ser desfeita.</small></p>
		<div slot="modal-footer">
			<a class="btn btn-info text-light" @click="closeModal()">Fechar</a>
			<a class="btn btn-danger text-light" @click="deleteBanco(clickedBanco.id)">Confirmar</a>
		</div>
	</b-modal>
</div>
<%= javascript_pack_tag 'bancos', 'data-turbolinks-track': 'reload' %>

app/views/bancos/new.html.erb
<h1>Cadastrar Banco</h1>

<%= render 'form', banco: @banco %>

<%= link_to 'Voltar', bancos_path %>

app/views/bancos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @banco.descricao %>
</p>

<p>
  <strong>Código:</strong>
  <%= @banco.codigo %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @banco.foto  %>
</p>
<%= link_to 'Edit', edit_banco_path(@banco) %> |
<%= link_to 'Back', bancos_path %>