config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  
  get 'pages/index'

  #Rotas montar selects
  get 'bancos/all'
  get 'contas/all'
  get 'pessoas/all'

  resources :contas
  resources :pessoas
  resources :bancos
  resources :movimentos
  
  devise_for :usuarios, :skip => [:registrations] 

  #Rotas JSON(País, Estado, Cidade)
  get 'enderecos/association'
  get 'enderecos/paises'
  get 'enderecos/:id/pais', to: 'enderecos#pais'
  get 'enderecos/estados'
  get 'enderecos/:id/estado', to: 'enderecos#estado'
  get 'enderecos/cidades'
  get 'enderecos/:id/cidade', to: 'enderecos#cidade'
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  enum tipo: [:Física, :Jurídica]
  belongs_to :endereco, optional: true,  dependent: :destroy
  accepts_nested_attributes_for :endereco, reject_if: :all_blank, allow_destroy: true
  belongs_to :pessoafisica, optional: true, dependent: :destroy
  accepts_nested_attributes_for :pessoafisica, reject_if: :all_blank, allow_destroy: true
  belongs_to :pessoajuridica, optional: true, dependent: :destroy
  accepts_nested_attributes_for :pessoajuridica, reject_if: :all_blank, allow_destroy: true
  has_many :contatos, :inverse_of => :pessoa, dependent: :delete_all
  accepts_nested_attributes_for :contatos, :allow_destroy => true
  
  validates :pessoajuridica, absence: true, if: :verificatipo_fisica?
  def verificatipo_fisica?
    tipo == "Física"
  end
  
  validates :pessoafisica, absence: true, if: :verifica_tipo_juridica?
  def verifica_tipo_juridica?
    tipo == "Jurídica"
  end
  
  def identificador
    if self.tipo == 'Física'
      return CPF.new(self.pessoafisica.cpf).formatted;
    end
    CNPJ.new(self.pessoajuridica.cnpj).formatted
  end
  
  def nome
    if self.tipo == 'Física'
      return self.pessoafisica.nome;
    end
    self.pessoajuridica.razaosocial
  end
  
  scope :nome, -> (nome) {
    joins("LEFT JOIN pessoafisicas ON pessoas.pessoafisica_id = pessoafisicas.id")
    .joins("LEFT JOIN pessoajuridicas ON pessoas.pessoajuridica_id = pessoajuridicas.id")    
    .where("pessoafisicas.nome like ? or pessoajuridicas.razaosocial like ?",  "%#{nome}%", "%#{nome}%") 
  }
  
  scope :identificador, -> (identificador) {
    joins("LEFT JOIN pessoafisicas ON pessoas.pessoafisica_id = pessoafisicas.id")
    .joins("LEFT JOIN pessoajuridicas ON pessoas.pessoajuridica_id = pessoajuridicas.id")    
    .where("pessoafisicas.cpf like ? or pessoajuridicas.cnpj like ?",  "%#{identificador}%", "%#{identificador}%") 
  }
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.where(nil) #Inicia Escopo
    @pessoas = @pessoas.nome(params[:nome]) if params[:nome].present?
    @pessoas = @pessoas.identificador(params[:identificador]) if params[:identificador].present?
    @pessoas = @pessoas.where(tipo: 'Física') if params[:fisica].present?
    @pessoas = @pessoas.where(tipo: 'Jurídica') if params[:juridica].present?
    
    @pessoas = @pessoas.paginate(:page => params[:page], :per_page => params[:per_page])
    respond_to do |format|
      format.html { render :index }
      format.json { render json: {pessoas: @pessoas.as_json(:include => [:pessoafisica, :pessoajuridica, :endereco, :contatos], methods: [:nome, :identificador]), total: @pessoas.total_entries}}
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
    @contato = @pessoa.contatos.build
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to(@pessoa, :notice => t('activerecord.successful.messages.created', :model => @pessoa.class.model_name.human))}
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render :json => { :errors => @pessoa.errors.full_messages }, :status => 422 }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to(@pessoa, :notice => t('activerecord.successful.messages.updated', :model => @pessoa.class.model_name.human))}
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render :json => { :errors => @pessoa.errors.full_messages }, :status => 422 }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to(@pessoa, :notice => t('activerecord.successful.messages.destroyed', :model => @pessoa.class.model_name.human))}
      format.json { render :json => { :errors => @pessoa.errors.full_messages }, :status => 422 }
    end
  end

  #GET /pessoas/all
  def all
    @pessoas = Pessoa.all
    respond_to do |format|
      format.json { render json: @pessoas, :only => [:id], :methods => [:nome] }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:tipo, pessoajuridica_attributes: [:id, :razaosocial, :cnpj, :nomefantasia, :_destroy], pessoafisica_attributes: [:id, :sexo, :cpf, :rg, :nome, :data_nascimento, :_destroy], endereco_attributes: [:id,:unidade_id,:estado_id,:cidade_id, :numero,:descricao,:complemento,:cep,:bairro, :_destroy], contatos_attributes: [:id, :tipo, :campo, :_destroy])
    end
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/pessoas/_contato_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :tipo %>
    <%= f.select :tipo, Contato.tipos.keys %>
  </div>
 
  <div class="field">
    <%= f.label :campo %>
    <%= f.text_field :campo %>
  </div>
  <%= link_to_remove_association "Remove Contato", f %>
</div>

app/views/pessoas/_endereco_fields.html.erb
<div class="nested-fields">
   <div class="field">
    <%= f.label :cidade_id %>
    <%= f.grouped_collection_select :cidade_id, Estado.order(:nome), :cidades, :nome, :id, :nome, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :cep, "CEP" %>
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :bairro %>
    <%= f.text_field :bairro %>
  </div>
   <div class="field">
    <%= f.label :descricao, "Descrição" %>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :numero, "Número" %>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :complemento %>
    <%= f.text_field :complemento %>
  </div>
  <%= link_to_remove_association "Remover Contato", f %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    cidades = $('#pessoa_endereco_attributes_cidade_id').html() 
    estados = $('#pessoa_endereco_attributes_estado_id').html()
    $('#pessoa_endereco_attributes_estado_id').change(function() {
      estado = $('#pessoa_endereco_attributes_estado_id :selected').text()
      opcoes = $(cidades).filter("optgroup[label='" + estado + "']").html();
      if (opcoes)
	      $('#pessoa_endereco_attributes_cidade_id').html(opcoes)
      else
        $('#pessoa_endereco_attributes_cidade_id').empty
    });
    $('#pessoa_endereco_attributes_unidade_id').change(function() {
      unidade = $('#pessoa_endereco_attributes_unidade_id :selected').text()
      opcoes = $(estados).filter("optgroup[label='" + unidade + "']").html();
      if (opcoes)
	      $('#pessoa_endereco_attributes_estado_id').html(opcoes)
      else
	      $('#pessoa_endereco_attributes_estado_id').empty
    });
  });
</script>

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.select :tipo, Pessoa.tipos.keys %>
  </div>

  <h4>Pessoa Física</h4>
  <div id="pessoafisica">
    <%= form.fields_for :pessoafisica do |pessoafisica| %>
      <%= render 'pessoafisica_fields', f: pessoafisica %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Pessoa Física', form, :pessoafisica %>
    </div>
  </div>

  <h4>Pessoa Jurídica</h4>
  <div id="pessoajuridica">
    <%= form.fields_for :pessoajuridica do |pessoajuridica| %>
      <%= render 'pessoajuridica_fields', f: pessoajuridica %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Pessoa Jurídica', form, :pessoajuridica %>
    </div>
  </div>

  <h4>Endereço</h4>
  <div id="endereco">
    <%= form.fields_for :endereco do |endereco| %>
      <%= render 'endereco_fields', f: endereco %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Endereço', form, :endereco %>
    </div>
  </div>
  
  <h4>Contatos</h4>
  <div id="contatos">
    <%= form.fields_for :contatos do |contato| %>
      <%= render 'contato_fields', f: contato %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Contato', form, :contatos %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/_pessoafisica_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :nome, "Nome" %>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf, "CPF"  %>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :rg, "RG" %>
    <%= f.text_field :rg %>
  </div>
  <div class="field">
    <%= f.label :sexo %>
    <%= f.select :sexo, Pessoafisica.sexos.keys %>
  </div>
  <div class="field">
    <%= f.label :data_nascimento %>
    <%= f.date_field :data_nascimento%>
  </div>
  <%= link_to_remove_association "Remover Pessoa Física", f %>
</div>

app/views/pessoas/_pessoajuridica_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :nomefantasia, "Nome Fantasia" %>
    <%= f.text_field :nomefantasia %>
  </div>
  <div class="field">
    <%= f.label :razaosocial, "Razão Social"  %>
    <%= f.text_field :razaosocial %>
  </div>
  <div class="field">
    <%= f.label :cnpj, "CNPJ" %>
    <%= f.text_field :cnpj %>
  </div>
  <%= link_to_remove_association "Remover Pessoa Jurídica", f %>
</div>

app/views/pessoas/edit.html.erb
<h1>Editar Favorecido</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/new.html.erb
<h1>Novo Favorecido</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Voltar', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @pessoa.tipo %>
</p>

<p>
  <strong>Pessoafisica:</strong>
  <%= @pessoa.pessoafisica %>
</p>

<p>
  <strong>Pessoajuridica:</strong>
  <%= @pessoa.pessoajuridica %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @pessoa.endereco %>
</p>

<%= link_to 'Editar', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Voltar', pessoas_path %>