config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  
  get 'pages/index'

  #Rotas montar selects
  get 'bancos/all'
  get 'contas/all'
  get 'pessoas/all'

  resources :contas
  resources :pessoas
  resources :bancos
  resources :movimentos
  
  devise_for :usuarios, :skip => [:registrations] 

  #Rotas JSON(País, Estado, Cidade)
  get 'enderecos/association'
  get 'enderecos/paises'
  get 'enderecos/:id/pais', to: 'enderecos#pais'
  get 'enderecos/estados'
  get 'enderecos/:id/estado', to: 'enderecos#estado'
  get 'enderecos/cidades'
  get 'enderecos/:id/cidade', to: 'enderecos#cidade'
end

app/models/movimento.rb
class Movimento < ApplicationRecord
    belongs_to :conta
    belongs_to :pessoa
    belongs_to :nota, optional: true
    accepts_nested_attributes_for :nota, reject_if: :all_blank, allow_destroy: true
    
    def favorecido
      self.pessoa.nome
    end
    
    def contabancaria
      self.conta.conta
    end
    
    def informacaonota
      if (!self.nota.nil?)
        self.nota.numero + ' - ' + self.nota.descricao
      end
    end
    
    scope :valor, -> (valor) { where("valor = ?", "#{valor}")}
    scope :data_competencia, -> (dataCompetenciaInicio) { where("data_competencia >= ?", "#{dataCompetenciaInicio}")}
    scope :data_competencia_final, -> (dataCompetenciaFinal) { where("data_competencia <= ?", "#{dataCompetenciaFinal}")}
    scope :pessoa, -> (pessoa) {
      joins("JOIN pessoas ON pessoas.id = movimentos.pessoa_id")
      .joins("LEFT JOIN pessoafisicas ON pessoas.pessoafisica_id = pessoafisicas.id")
      .joins("LEFT JOIN pessoajuridicas ON pessoas.pessoajuridica_id = pessoajuridicas.id")    
      .where("pessoafisicas.nome like ? or pessoajuridicas.razaosocial like ?",  "%#{pessoa}%", "%#{pessoa}%") 
    }
    scope :receita, -> (receita) { where("valor > 0")}
    scope :despesa, -> (despesa) { where("valor < 0")}
    scope :conta_id, -> (contaId) { where("conta_id = ?", "#{contaId}")}
    scope :descricao, -> (descricao) { where("descricao like ?", "%#{descricao}%")}
end
 

app/controllers/movimentos_controller.rb
class MovimentosController < ApplicationController
  before_action :set_movimento, only: [:show, :edit, :update, :destroy]

  # GET /movimentos
  # GET /movimentos.json
  def index
    @movimentos = Movimento.where(nil) #Inicia Escopo
    @movimentos = @movimentos.data_competencia(params[:dataCompetenciaInicio]) if params[:dataCompetenciaInicio].present?
    @movimentos = @movimentos.data_competencia_final(params[:dataCompetenciaFinal]) if params[:dataCompetenciaFinal].present?
    @movimentos = @movimentos.pessoa(params[:pessoa]) if params[:pessoa].present?
    @movimentos = @movimentos.valor(params[:valor]) if params[:valor].present?
    @movimentos = @movimentos.receita(params[:receita]) if params[:receita].present?
    @movimentos = @movimentos.despesa(params[:despesa]) if params[:despesa].present?
    @movimentos = @movimentos.conta_id(params[:contaId]) if params[:contaId].present?
    @movimentos = @movimentos.descricao(params[:descricao]) if params[:descricao].present?
    
    @movimentos = @movimentos.paginate(:page => params[:page], :per_page => params[:per_page])
    respond_to do |format|
      format.html { render :index }
      format.json { render json: {movimentos: @movimentos.as_json(:include => [:conta, :pessoa, :nota], methods: [:favorecido, :contabancaria, :informacaonota]), total: @movimentos.total_entries}}
    end
  end

  # GET /movimentos/1
  # GET /movimentos/1.json
  def show
  end

  # GET /movimentos/new
  def new
    @movimento = Movimento.new
    @contas = Conta.all
  end

  # GET /movimentos/1/edit
  def edit
    @contas = Conta.all
  end

  # POST /movimentos
  # POST /movimentos.json
  def create
    @movimento = Movimento.new(movimento_params)

    respond_to do |format|
      if @movimento.save
        format.html { redirect_to(@movimento, :notice => t('activerecord.successful.messages.created', :model => @movimento.class.model_name.human))}
        format.json { render :show, status: :created, location: @movimento }
      else
        format.html { render :new }
        format.json { render :json => { :errors => @movimento.errors.full_messages }, :status => 422 }
      end
    end
  end

  # PATCH/PUT /movimentos/1
  # PATCH/PUT /movimentos/1.json
  def update
    respond_to do |format|
      if @movimento.update(movimento_params)
        format.html { redirect_to(@movimento, :notice => t('activerecord.successful.messages.updated', :model => @movimento.class.model_name.human))}
        format.json { render :show, status: :ok, location: @movimento }
      else
        format.html { render :edit }
        format.json { render :json => { :errors => @movimento.errors.full_messages }, :status => 422 }
      end
    end
  end

  # DELETE /movimentos/1
  # DELETE /movimentos/1.json
  def destroy
    @movimento.destroy
    respond_to do |format|
      format.html { redirect_to(@movimento, :notice => t('activerecord.successful.messages.destroyed', :model => @movimento.class.model_name.human))}
      format.json { render :json => { :errors => @movimento.errors.full_messages }, :status => 422 }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimento
      @movimento = Movimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movimento_params
      params.require(:movimento).permit(:data_competencia, :data_vencimento, :descricao, :valor, :conta_id, :pessoa_id, nota_attributes: [:id, :data, :descricao, :numero, :codigo, :_destroy])
    end	    
end

app/helpers/movimentos_helper.rb
module MovimentosHelper
end

app/views/movimentos/_form.html.erb
<%= form_with(model: movimento, local: true) do |form| %>
  <% if movimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movimento.errors.count, "error") %> prohibited this movimento from being saved:</h2>

      <ul>
      <% movimento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :data_competencia, "Data da competência" %>
    <%= form.date_field :data_competencia, :class => "form-control"%>
  </div>
  
  <div class="field form-group">
    <%= form.label :data_vencimento, "Data do vencimento" %>
    <%= form.date_field :data_vencimento, :class => "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :descricao, "Descrição" %>
    <%= form.text_field :descricao, :class => "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :valor %>
    <%= form.number_field :valor, :step => 0.01, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :conta_id %>
    <%= form.select :conta_id, @contas.collect { |conta| [conta.conta_numero, conta.id] }, {}, { :class => 'form-control' } %>
  </div>
  <div class="actions">
    <%= form.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/movimentos/edit.html.erb
<h1>Editar movimento</h1>

<%= render 'form', movimento: @movimento %>

app/views/movimentos/index.html.erb
<div id="movimentosApp" v-cloak class="container">
	<div class="table-wrapper">
	  <div class="table-title">
	      <div class="row">
	          <div class="col-sm-6">
	            <h2 class="text-light">Gerenciar <b>Movimentos</b></h2>
	          </div>
	      		<div class="col-sm-6">
	      			<a href="#formMovimentoModal" class="btn btn-success" data-toggle="modal" @click="mountCreateForm()"><i class="material-icons">&#xE147;</i> <span>Novo</span></a>
	      			<a href="#deleteMovimentoModal" class="btn btn-danger" data-toggle="modal" @click="mountMultipleDeleteForm()"><i class="material-icons">&#xE15C;</i> <span>Apagar</span></a>						
	      			<a class="btn btn-warning" @click="createPDF()"><i class="material-icons">&#xE873;</i> <span>PDF</span></a>
	      		</div>
	      </div>
	  </div>
	  <div class="search-wrapper">
		  <div class="form-row align-items-center">
		    <div class="col-md-3">
		      <label class="sr-only" for="inlineFormInput"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Data - Início</div>
		        </div>
		        <input class="form-control" type="date" id="dataCompetenciaI" v-model="dataCompetenciaInicio">
		      </div>
		    </div>
		    <div class="col-md-3">
		      <label class="sr-only" for="inlineFormInput"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Data - Final</div>
		        </div>
		        <input class="form-control" type="date" id="dataCompetenciaF" v-model="dataCompetenciaFinal">
		      </div>
		    </div>
		    <div class="col-md-3">
		      <label class="sr-only" for="contaBanco"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Conta</div>
		        </div>
            <select v-model = 'contaId' class="form-control">
              <option v-for="conta in contas" v-bind:value="conta.id">
                {{conta.conta}}
              </option>
            </select>
		      </div>
		    </div>
		    <div class="col-md-2">	
		      <label class="sr-only" for="tipoMovimento"></label>	
		      <div class="input-group mb-2">	
		        <div class="input-group-prepend">	
		          <div class="input-group-text" style="background-color:transparent">Tipo</div>	
		        </div>	
            <select v-model = 'tipoMovimento' class="form-control">	
              <option v-for="tipo in tipos" v-bind:value="tipo.value">	
                {{tipo.descricao}}	
              </option>	
            </select>	
		      </div>	
		    </div>
		   </div>
		   <div class="form-row align-items-center">
		   	 <div class="col-md-3">
		      <label class="sr-only" for="inlineFormInputGroup"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Descrição</div>
		        </div>
		        <input type="text" class="form-control" id="descricao" v-model="descricao">
		      </div>
		    </div>
		    <div class="col-md-6">
		      <label class="sr-only" for="pessoaNome"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Favorecido/Sacado</div>
		        </div>
		        <input type="text" class="form-control" id="pessoaNome" v-model="pessoaNome">
		      </div>
		    </div>
		    <div class="col-md-2">
		      <label class="sr-only" for="valor"></label>
		      <div class="input-group mb-2">
		        <div class="input-group-prepend">
		          <div class="input-group-text" style="background-color:transparent">Valor</div>
		        </div>
		        <input step="0.01" class="form-control" type="number" id="valor" v-model="valor">
		      </div>
		    </div>
		     <div class="col-auto">
			  <a class="btn btn-primary mb-2 text-light" @click="searchMovimentos()"><span class="fa fa-search"></span></a>
			</div>
		  </div>
		</div>
	  <table class="table table-striped table-hover">
	    <thead>
	        <tr>
				<th>
					<span class="custom-checkbox">
						<input type="checkbox" id="selectAll" v-model="allSelected" @click="selectAll">
						<label for="selectAll"></label>
					</span>
				</th>
            <th>Data Competência</th>
	          <th>Fav/Sac</th>
	          <th>Valor</th>
	          <th>Ações</th>
	        </tr>
	    </thead>
	    <tbody>
	        <tr v-for="(movimento, index) in movimentos">
	    			<td>
	    				<span class="custom-checkbox">
	    					<input type="checkbox" :id="'checkbox'+movimento.id" value="1" v-model="movimentos[index].selected" @click="select">
	    					<label :for="'checkbox'+movimento.id"></label>
	    				</span>
	    			</td>
            <td @click="mountShowModal(movimento)">{{ new Date(movimento.data_competencia+"T00:00:00").toLocaleDateString() }}</td>
            <td>{{ movimento.favorecido }}</td>
            <td v-bind:class="[movimento.valor > 0 ? 'text-success' : 'text-danger', 'font-weight-bold']">{{ movimento.valor }}</td>
            <td>
	            <a href="#deleteMovimentoModal" data-toggle="modal" class="edit" @click="mountEditForm(movimento)"><i class="material-icons" data-toggle="tooltip" title="Editar">&#xE254;</i></a>
	            <a href="#deleteMovimentoModal" data-toggle="modal" class="delete" @click="mountDeleteForm(movimento)"><i class="material-icons" data-toggle="tooltip" title="Apagar">&#xE872;</i></a>
	        </td>
	        </tr>
	    </tbody>
	  </table>
    <div class="text-center" v-if="loading">
      <div class="spinner-border" role="status">
        <span class="sr-only">Carregando...</span>
      </div>
    </div>
    <div class="mt-3 text-right" v-if="total > 10">
      <b-pagination align="right" :total-rows="total" :per-page="10" @change="changePage" />
    </div>
    <div class="hint-text">Mostrando <b>{{movimentos.length }}</b> registros</div>
    <br>
	</div>
	
	<b-modal ref="formMovimentoModal" title="Movimento">
			<form>
				<div v-if="!nota">
				  <div class="field form-group">
				    <label for="movimento_data_competencia">Data da competência</label>
				    <input class="form-control" type="date" name="movimento[data_competencia]" id="movimento_data_competencia" v-model="clickedMovimento.data_competencia">
				  </div>
				  
				  <div class="field form-group">
				    <label for="movimento_data_vencimento">Data do vencimento</label>
				    <input class="form-control" type="date" name="movimento[data_vencimento]" id="movimento_data_vencimento" v-model="clickedMovimento.data_vencimento">
				  </div>
				
				  <div class="field form-group">
				    <label for="movimento_descricao">Descrição</label>
				    <input class="form-control" type="text" name="movimento[descricao]" id="movimento_descricao" v-model="clickedMovimento.descricao">
				  </div> 
				
				  <div class="field form-group">
				    <label for="movimento_pessoa_id">Favorecido/Sacado</label>
				    <v-select v-model="clickedMovimento.favorecido" label="nome" placeholder="Selecione" :options="pessoas"><span slot="no-options">Não foi encontrado.</span></v-select>
				  </div>
				  
				   <div class="field form-group">
				    <label for="movimento_pessoa_id">Conta</label>
				    <select v-model = 'clickedMovimento.conta_id' class="form-control">
				    	<option v-for="conta in contas" v-bind:value="conta.id">
				    		{{conta.conta}}
				    	</option>
				    </select>
				  </div>
						<div class="field form-group">
							<label for="movimento_valor">Valor</label>
							<input step="0.01" class="form-control" type="number" name="movimento[valor]" id="movimento_valor" v-model="clickedMovimento.valor">
						</div>
						<div class="field form-group">
							<b-form-checkbox switch v-model="clickedMovimento.valor > 0" name="check-button" @change="alteraTipo()">
								<b> Tipo de movimento: <span v-bind:class="[clickedMovimento.valor > 0 ? 'text-success' : 'text-danger', 'font-weight-bold']"> {{ clickedMovimento.valor > 0 ? "Receita" : "Despesa" }}</span></b>
							</b-form-checkbox>
						</div>
			  </div>
			  
				<div v-if="nota">
					<div class="field form-group">
				    <label for="movimento_nota_data">Data</label>
				    <input class="form-control" type="date" name="movimento_nota[data]" id="movimento_nota_data" v-model="clickedMovimento.nota.data">
				  </div>
				  <div class="field form-group">
				    <label for="movimento_nota_descricao">Descrição</label>
				    <input class="form-control" type="text" name="movimento_nota[descricao]" id="movimento_nota_descricao" v-model="clickedMovimento.nota.descricao">
				  </div>
				  
				  <div class="form-row">
				    <div class="field form-group col-md-7">
				      <label for="movimento_numero_nota">Número da nota</label>
				      <input class="form-control" type="number" name="movimento_nota[numero]" id="movimento_nota_numero" v-model="clickedMovimento.nota.numero">
				    </div>
				    <div class="field form-group col-md-4">
				      <label for="movimento_codigo_nota">Código da nota</label>
				      <input class="form-control" type="number" name="movimento_nota[codigo]" id="movimento_nota_codigo" v-model="clickedMovimento.nota.codigo">
				    </div>
				  </div>
			  </div>
			  
			</form>
			<div slot="modal-footer">
				<a class="btn btn-secondary text-light" @click="closeModal">Fechar</a>
				<a class="btn btn-info text-light" @click="nota = true" v-if="!nota">Nota Fiscal</a>
				<a class="btn btn-info text-light" @click="nota = false" v-if="nota">Movimento</a>
				<a class="btn btn-success text-light" @click="createMovimento(clickedMovimento)" v-if="create"><span v-if="loading" class="spinner-border spinner-border-sm"></span> Salvar</a>
				<a class="btn btn-info text-light" @click="updateMovimento(clickedMovimento)" v-if="!create"> Atualizar</a>
			</div>
	</b-modal>
	<b-modal ref="deleteMovimentoModal" title="Apagar Movimento">
			<p>Data Competência: {{ new Date(clickedMovimento.data_competencia+"T00:00:00").toLocaleDateString()}}</p>
			<p>Descrição: {{clickedMovimento.descricao}}</p>
			<p>Favorecido: {{clickedMovimento.favorecido}}</p>
			<p>Conta: {{clickedMovimento.contabancaria}}</p>
			<p class="text-danger"><small>Esta ação não poderá ser desfeita.</small></p>
			<div slot="modal-footer">
				<a class="btn btn-info text-light" @click="closeModal()">Fechar</a>
				<a class="btn btn-danger text-light" @click="deleteMovimento(clickedMovimento.id)">Confirmar</a>
			</div>
	</b-modal>
	<b-modal ref="showMovimentoModal" title="Exibir Movimento">
		<p><strong>Descrição</strong>: {{clickedMovimento.descricao}}</p>
		<p><strong>Data Competência</strong>: {{ new Date(clickedMovimento.data_competencia+"T00:00:00").toLocaleDateString()}}</p>
		<p><strong>Favorecido</strong>: {{clickedMovimento.favorecido}}</p>
		<p><strong>Conta</strong>: {{clickedMovimento.contabancaria}}</p>
		<p><strong>Valor</strong>: <span v-bind:class="[clickedMovimento.valor > 0 ? 'text-success' : 'text-danger', 'font-weight-bold']">{{clickedMovimento.valor}}</span></p>
		<div v-if="clickedMovimento.nota.descricao">
			<p class="text-center font-weight-bold">Informações sobre nota:</p>
			<p><strong>Descrição</strong>: {{clickedMovimento.nota.descricao}}</p>
			<p><strong>Data</strong>: {{ new Date(clickedMovimento.nota.data+"T00:00:00").toLocaleDateString() }}</p>
			<p><strong>Número</strong>: {{clickedMovimento.nota.numero}} - {{clickedMovimento.nota.codigo}}</p>
		</div>
		<div slot="modal-footer">
			<a class="btn btn-info text-light" @click="closeModal()">Fechar</a>
		</div>
	</b-modal>
</div>
<%= javascript_pack_tag 'movimentos', 'data-turbolinks-track': 'reload' %>

app/views/movimentos/new.html.erb
<h1>Cadastrar movimento</h1>

<%= render 'form', movimento: @movimento %>

app/views/movimentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data da competência:</strong>
  <%= @movimento.data_competencia.to_date.to_s(:rfc822) %>
</p>

<p>
  <strong>Data do vencimento:</strong>
  <%= @movimento.data_vencimento.to_date.to_s(:rfc822) %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @movimento.descricao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @movimento.valor %>
</p>

<%= link_to 'Edit', edit_movimento_path(@movimento) %> |
<%= link_to 'Back', movimentos_path %>