config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  
  get 'pages/index'

  #Rotas montar selects
  get 'bancos/all'
  get 'contas/all'
  get 'pessoas/all'

  resources :contas
  resources :pessoas
  resources :bancos
  resources :movimentos
  
  devise_for :usuarios, :skip => [:registrations] 

  #Rotas JSON(País, Estado, Cidade)
  get 'enderecos/association'
  get 'enderecos/paises'
  get 'enderecos/:id/pais', to: 'enderecos#pais'
  get 'enderecos/estados'
  get 'enderecos/:id/estado', to: 'enderecos#estado'
  get 'enderecos/cidades'
  get 'enderecos/:id/cidade', to: 'enderecos#cidade'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
   def serializable_hash(options={})
    options[:except] ||= []
    options[:except] << :created_at unless (options[:include] == :created_at) || (options[:include].kind_of?(Array) && (options[:include].include? :created_at))
    options[:except] << :updated_at unless (options[:include] == :updated_at) || (options[:include].kind_of?(Array) && (options[:include].include? :updated_at))
    options.delete(:include) if options[:include] == :created_at
    options.delete(:include) if options[:include] == :updated_at
    options[:include] -= [:created_at, :updated_at] if options[:include].kind_of?(Array)
    super(options)
  end
  
end

app/models/banco.rb
class Banco < ApplicationRecord
  has_many :contas, :dependent => :delete_all
  
  validates :codigo, numericality: true, presence: true
  validates :descricao, presence: true
  
  def busca(id)
    Banco.find(id)
  end
  
  scope :codigo, -> (codigo) { where("codigo like ?", "%#{codigo}%")}
  scope :descricao, -> (descricao) { where("descricao like ?", "%#{descricao}%")}
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  validates :nome, presence: true
  def to_s
     self.nome + ' - ' + self.estado.nome;
  end
end

app/models/conta.rb
class Conta < ApplicationRecord
  belongs_to :banco
  has_many :movimentos
  
  validates :conta_numero, numericality: true, presence: true
  validates :agencia_numero, numericality: true, presence: true
  validates :conta_digito, numericality: { less_than_or_equal_to: 9,  only_integer: true }
  validates :agencia_digito, numericality: { less_than_or_equal_to: 9,  only_integer: true }
  
  def saldo
    movimentos.sum(&:valor)
  end
  
  def conta
    self.conta_numero + "-" + self.conta_digito.to_s
  end
  
  def agencia
    self.agencia_numero + "-" + self.agencia_digito.to_s  
  end

  scope :conta_numero, -> (conta_numero) { where("conta_numero like ?", "%#{conta_numero}%")}
  scope :conta_descricao, -> (conta_descricao) { where("descricao like ?", "%#{conta_descricao}%")}
  scope :agencia_numero, -> (agencia_numero) { where("agencia_numero like ?", "%#{agencia_numero}%")}
  scope :banco_id, -> (bancoId) { where("banco_id = ?", "#{bancoId}")}
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :pessoa, :inverse_of => :contatos
  enum tipo: [
    :Email,
	  :Telefone,
	  :Celular]
	validates :campo, presence: true
	validates :tipo, presence: true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cidade
  validates :numero, numericality: true, presence: true
  validates :complemento, presence: true
  validates :cep, numericality: true, presence: true
  validates :bairro, presence: true
  validates :descricao, presence: true
  
  def to_s 
    self.descricao + ', ' + self.numero.to_s + ', ' + self.cidade.to_s;
  end
end

app/models/estado.rb
class Estado < ApplicationRecord
 belongs_to :unidade
  has_many :cidades
  validates :nome, presence: true
  validates :sigla, length: { minimum: 2 }, presence: true
  
  def to_s
   self.nome + ", " + self.unidade.nome;
  end
end

app/models/movimento.rb
class Movimento < ApplicationRecord
    belongs_to :conta
    belongs_to :pessoa
    belongs_to :nota, optional: true
    accepts_nested_attributes_for :nota, reject_if: :all_blank, allow_destroy: true
    
    def favorecido
      self.pessoa.nome
    end
    
    def contabancaria
      self.conta.conta
    end
    
    def informacaonota
      if (!self.nota.nil?)
        self.nota.numero + ' - ' + self.nota.descricao
      end
    end
    
    scope :valor, -> (valor) { where("valor = ?", "#{valor}")}
    scope :data_competencia, -> (dataCompetenciaInicio) { where("data_competencia >= ?", "#{dataCompetenciaInicio}")}
    scope :data_competencia_final, -> (dataCompetenciaFinal) { where("data_competencia <= ?", "#{dataCompetenciaFinal}")}
    scope :pessoa, -> (pessoa) {
      joins("JOIN pessoas ON pessoas.id = movimentos.pessoa_id")
      .joins("LEFT JOIN pessoafisicas ON pessoas.pessoafisica_id = pessoafisicas.id")
      .joins("LEFT JOIN pessoajuridicas ON pessoas.pessoajuridica_id = pessoajuridicas.id")    
      .where("pessoafisicas.nome like ? or pessoajuridicas.razaosocial like ?",  "%#{pessoa}%", "%#{pessoa}%") 
    }
    scope :receita, -> (receita) { where("valor > 0")}
    scope :despesa, -> (despesa) { where("valor < 0")}
    scope :conta_id, -> (contaId) { where("conta_id = ?", "#{contaId}")}
    scope :descricao, -> (descricao) { where("descricao like ?", "%#{descricao}%")}
end
 

app/models/nota.rb
class Nota < ApplicationRecord
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  enum tipo: [:Física, :Jurídica]
  belongs_to :endereco, optional: true,  dependent: :destroy
  accepts_nested_attributes_for :endereco, reject_if: :all_blank, allow_destroy: true
  belongs_to :pessoafisica, optional: true, dependent: :destroy
  accepts_nested_attributes_for :pessoafisica, reject_if: :all_blank, allow_destroy: true
  belongs_to :pessoajuridica, optional: true, dependent: :destroy
  accepts_nested_attributes_for :pessoajuridica, reject_if: :all_blank, allow_destroy: true
  has_many :contatos, :inverse_of => :pessoa, dependent: :delete_all
  accepts_nested_attributes_for :contatos, :allow_destroy => true
  
  validates :pessoajuridica, absence: true, if: :verificatipo_fisica?
  def verificatipo_fisica?
    tipo == "Física"
  end
  
  validates :pessoafisica, absence: true, if: :verifica_tipo_juridica?
  def verifica_tipo_juridica?
    tipo == "Jurídica"
  end
  
  def identificador
    if self.tipo == 'Física'
      return CPF.new(self.pessoafisica.cpf).formatted;
    end
    CNPJ.new(self.pessoajuridica.cnpj).formatted
  end
  
  def nome
    if self.tipo == 'Física'
      return self.pessoafisica.nome;
    end
    self.pessoajuridica.razaosocial
  end
  
  scope :nome, -> (nome) {
    joins("LEFT JOIN pessoafisicas ON pessoas.pessoafisica_id = pessoafisicas.id")
    .joins("LEFT JOIN pessoajuridicas ON pessoas.pessoajuridica_id = pessoajuridicas.id")    
    .where("pessoafisicas.nome like ? or pessoajuridicas.razaosocial like ?",  "%#{nome}%", "%#{nome}%") 
  }
  
  scope :identificador, -> (identificador) {
    joins("LEFT JOIN pessoafisicas ON pessoas.pessoafisica_id = pessoafisicas.id")
    .joins("LEFT JOIN pessoajuridicas ON pessoas.pessoajuridica_id = pessoajuridicas.id")    
    .where("pessoafisicas.cpf like ? or pessoajuridicas.cnpj like ?",  "%#{identificador}%", "%#{identificador}%") 
  }
end

app/models/pessoafisica.rb
class Pessoafisica < ApplicationRecord
  belongs_to :pessoa, optional: true,  dependent: :destroy
  enum sexo: [:Masculino, :Feminino]
  validates :cpf, presence: true
  validates :rg, presence: true
  validates :nome, presence: true
  validates :data_nascimento, presence: true
  def cpf_formatado
    CPF.new(self.cpf).formatted;
  end
end

app/models/pessoajuridica.rb
class Pessoajuridica < ApplicationRecord
  belongs_to :pessoa, optional: true,  dependent: :destroy
  validates :razaosocial, presence: true
  validates :cnpj, presence: true
  validates :nomefantasia, presence: true
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  has_many :estados
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movimentos_helper.rb
module MovimentosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Projeto</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>
   <body>
     <% if usuario_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-black">
          <a class="navbar-brand py-2" href="#"><%= image_tag("san-juan.png", :alt => "San Juan Advogados", :height => '50') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="/">Início</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Cadastro Financeiro
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/bancos">Bancos</a>
                  <a class="dropdown-item" href="/contas">Contas</a>
                  <%= link_to 'Favorecidos/Sacados', 'pessoas', {:class => 'dropdown-item'} %>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/movimentos">Movimentação</a>
              </li>
            </ul>
            <span class="navbar-text">
             <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to 'Logout', destroy_usuario_session_path,  { :class => "nav-link", method: :delete } %>        
              </li>
            </ul>
            </span>
          </div>
        </nav>
        <% else %>
      <nav class="menu" id="theMenu">
         <div class="menu-wrap">
            <h1 class="logo"><a href="index.html#home">San Juan</a></h1>
            <i class="fa fa-times-circle menu-close"></i>
            <% if usuario_signed_in? %>
            <a href=""class="smoothscroll">Financeiro</a>
            <%= link_to 'Bancos', 'bancos', {:class => 'nav-link'} %>
            <%= link_to 'Contas', 'contas', {:class => 'nav-link'} %>
            <%= link_to 'Favorecidos/Sacados', 'pessoas', {:class => 'nav-link'} %>
            <%= link_to 'Movimentação', 'movimentos', {:class => 'nav-link'} %>
            <%= link_to 'Logout', destroy_usuario_session_path,  { :class => "nav-link", method: :delete } %>
            <% else %>
            <a href="#home" class="smoothscroll">Início</a>
            <a href="#services" class="smoothscroll">Serviços</a>
            <a href="#about" class="smoothscroll">Sobre</a>
            <a href="#mapa" class="smoothscroll">Localização</a>
            <a href="#contact" class="smoothscroll">Contato</a>
            <%= link_to 'Login', new_usuario_session_path, { :class => "nav-link" }  %> 
            <% end %>
         </div>
         <!-- Menu button -->
         <div id="menuToggle"><i class="fa fa-bars"></i></div>
      </nav>
      <% end %>
      <%= yield %>
      <div id="copyrights">
         <div>
            <p>
               &copy; Copyrights <strong>San Juan</strong>. Direitos Reservados
            </p>
         </div>
      </div>
   </body>
</html>